- name: restart logstash
  service: name=logstash state=restarted

- name: restart elasticsearch
  service: name=elasticsearch state=restarted

- name: restart kibana
  service: name=kibana state=restarted

- name: restart firewalld
  service: name=firewalld state=restarted

- name: reload systemd
  command: systemctl daemon-reload
